version: '1'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "appointment_db"
      MYSQL_USER: "saba"
      MYSQL_PASSWORD: "idea"
    ports:
      - "3306:3306"
    volumes:
      - ./SQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  php-app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "80:80"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - mysql:db
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_ARBITRARY: 1

volumes:
  mysql-data:
